### model
model_name_or_path: /mnt/coai-nas/yibai/LLaMA-Factory/saves/mistral/m_sft
flash_attn: fa2

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
# stage: dpo
# do_train: true
# finetuning_type: lora
# lora_target: all
# pref_beta: 0.1
# pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: preference_data
template: mistral
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/mistral/m_sdpo
logging_steps: 1
save_strategy: "no"
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 5.0e-7
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
seed: 11

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
