### model
model_name_or_path: /mnt/coai-nas/yibai/LLMs/Meta-Llama-3.1-8B-Instruct
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: sft_data
template: mistral
cutoff_len: 4096
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/mistral/m_sft #saves/llama/sft_1
logging_steps: 8
save_strategy: "no" #epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 3.0e-6 #1.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
seed: 11