FROM nvcr.io/nvidia/pytorch:25.06-py3

ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_ROOT_USER_ACTION=ignore

ENV PIP_CONSTRAINT=""

RUN pip install --upgrade \
    pip setuptools setuptools_scm wheel

RUN pip uninstall -y torch torchvision torch-tensorrt pytorch-triton

RUN pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu129

RUN pip install \
    "opencv-python-headless==4.11.0.86"

RUN apt-get update && apt-get install -y zip openjdk-21-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

RUN pip install \
    "megatron-core>=0.13.0,<0.14.0" "deepspeed==0.16.4"

RUN pip uninstall -y flash-attn && \
    pip install \
    --no-build-isolation \
    --trusted-host <your-pypi-mirror> \
    --index-url https://<your-pypi-mirror>/pypi/simple/ \
    "flash-attn==2.7.4.post1" "flash-linear-attention"

RUN pip install vllm==0.11.0 \
   