# basic
seed: 42
device: 'cuda'
model_name: 't5'
datatype: 'linear'
enable_uda_relative_pos: False

tokenizer_path: '/Unif/model_save/Metaall/config_and_tokenizer'
special_token_path: './cleanout_datasets/special_tokens.txt'
data_processor: 'linear'

modified_default_plm_config: True
plms_dropout_rate: 0.1

# training

train_type: 'finetune'
matrix: "all"
position_style: "0"
dist_train: False
experiment_name: 'finetuning_linear_base_on_totto_2e-4'
init_model_path: '/Unif/model_save/Metaall/models/epoch_4_step_262145_bleu_9.9600.pkl'
max_epochs: 80
max_steps: -1
early_stopping_patience: 8
start_eval_from: 0
eval_every: 1
max_keep_checkpoints: -1
report_every: 100
saved_dir: './finetuning/totto_linear'

learner: fairseq_adafactor
learning_rate: 2e-04
adam_epsilon: 0.00000001
max_grad_norm: 2.0
lr_scheduler: 'none'
warmup_steps: 0

# training data
train_file_src: './cleanout_datasets/totto_with_unified_graph/totto_train_data_mac.jsonl'
train_n_example: -1
train_batch_size: 8
max_source_length: 1024
max_target_length: -1
train_num_workers: 5


# evaluate data
eval_noise_data: False
eval_task_source_prefix: "describe the following data: "
val_metric: bleu
eval_file_src: './cleanout_datasets/totto_with_unified_graph/totto_dev.json'
eval_n_example: -1
eval_batch_size: 16
num_beams: 5
eval_max_source_length: 1024
eval_max_target_length: 128
eval_num_workers: 5