# basic
seed: 42
device: 'cuda'
model_name: 'uda'
datatype: 'graph'
enable_uda_relative_pos: False
# tokenizer_path: '/data/nt12_ssd_gluster/myself/pretrained_models/t5-small'
tokenizer_path: 't5-large'
special_token_path: './cleanout_datasets/special_tokens.txt'
data_processor: 'uda'
task_source_prefix: 'Describe the following data: '
eval_task_source_prefix: "describe the following data: "
modified_default_plm_config: True
plms_dropout_rate: 0.1

# training
train_type: 'finetune'
dist_train: False
experiment_name: 'finetuning_t5_large_uda_on_totto_2e-4_1.8'
init_model_path: 't5-large'
max_epochs: 10
max_steps: -1
early_stopping_patience: 8
start_eval_from: 0
eval_every: 1
max_keep_checkpoints: -1
report_every: 100
saved_dir: '/root/data/guanbao/finetuning/totto_graph'

learner: fairseq_adafactor
learning_rate: 2e-04
adam_epsilon: 0.00000001
max_grad_norm: 2.0
lr_scheduler: 'none'
warmup_steps: 0

# training data
train_file_src: '/root/data/liliang/experiments/UnifiedData2TextPretrain/cleanout_datasets/totto_with_unified_graph/totto_train_data_mac.jsonl'
train_n_example: -1
train_batch_size: 8
max_source_length: 1024
max_target_length: -1
train_num_workers: 5


# evaluate data
eval_noise_data: False
val_metric: bleu
eval_file_src: '/root/data/liliang/experiments/UnifiedData2TextPretrain/cleanout_datasets/totto_with_unified_graph/totto_dev_data.jsonl'
eval_n_example: -1
eval_batch_size: 32
num_beams: 5
eval_max_source_length: 1024
eval_max_target_length: 128
eval_num_workers: 5
